from pathlib import Path
import re

path = Path("main.tex")
text = path.read_text(encoding="utf-8")

def replace_between(source: str, start: str, end: str, replacement: str) -> str:
    i = source.find(start)
    if i < 0:
        raise RuntimeError(f"Missing start marker: {start}")
    j = source.find(end, i + len(start))
    if j < 0:
        raise RuntimeError(f"Missing end marker: {end}")
    return source[:i] + replacement.strip() + "\n\n" + source[j:]

ABSTRACT = r"""\begin{abstract}
Policy optimization in reinforcement learning with verifiable rewards repeatedly updates a
learner using data generated by a fixed rollout policy.  As the learner moves away from that
policy, the nominal batch size can substantially overstate the amount of information available
for the next update.  We study this problem at the level of the policy-gradient estimator
itself.  Viewing the gradient as a vector-valued importance-sampling estimator, we show that
its mean-squared error scales inversely with sequence effective sample size (ESS), where
$\mathrm{ESS}=N\exp\{-D_2(P_\theta\|Q)\}$.  Combining this reliability bound with a smoothness
argument yields a high-probability lower bound on the population improvement of an adaptive
gradient step.  The result makes the statistical mechanism explicit: larger ESS shrinks the
gradient-error radius, permits a larger certified step, and increases the guaranteed
improvement.  A one-pass disjoint-minibatch construction supplies the conditional freshness
needed by the theory, with an extension to intact prompt groups.  An exactly evaluable
contextual bandit verifies the predicted relation among ESS, gradient error, and harmful
updates, while language-model experiments show that sequence ESS remains an informative
operational diagnostic at scale.
\end{abstract}"""

INTRO = r"""\section{Introduction}

Reinforcement learning with verifiable rewards (RLVR) alternates between collecting a batch
of responses and optimizing a policy on that fixed batch.  Reusing the rollout is statistically
efficient, but it creates a moving-target problem: after several updates, the current policy no
longer matches the policy that generated the data.  The practical consequence is familiar.
Permissive updates can produce rapid early improvement, yet the same training run may become
unstable only after substantial reuse of the rollout.  Figure~\ref{fig:llm-motivation}
illustrates this delayed transition in Qwen3-30B-A3B training.

\begin{figure}[htbp]
  \centering
  \includegraphics[width=\linewidth]{figures_mains/motivation/overall.pdf}
  \caption{Empirical motivation in Qwen3-30B-A3B RLVR.  Two permissive
  coefficient-capped updates improve rapidly and fail only after normalized
  sequence ESS nearly vanishes.  The dotted line marks the prespecified $0.1$
  diagnostic studied later.}
  \label{fig:llm-motivation}
\end{figure}

The central question is therefore statistical: \emph{when does a fixed rollout still support
a reliable policy-gradient update for the current learner?}  A ratio threshold describes an
individual sample, and an update count records how long the rollout has been reused, but neither
directly measures the amount of effective information retained by the batch.  Sequence effective
sample size (ESS) does.  If $W=dP_\theta/dQ$ is the complete-response likelihood ratio, then
$\mathrm{ESS}=N/\mathbb E_Q[W^2]=N\exp\{-D_2(P_\theta\|Q)\}$.  Thus the order-two
R\'enyi divergence converts policy mismatch into an effective sample count.

This connection is classical for scalar importance-sampling estimators
\citep{metelli2018pois,metelli2020is}.  The missing link for our setting is the
gradient itself.  A reliable estimate of the sampled reward does not in general imply a
reliable derivative.  We therefore treat the policy gradient directly as a vector-valued
importance-sampling estimand.  Under a normalized weighted second-moment condition on the
gradient contribution, the conditional mean-squared error of the estimator is at most
$\sigma_g^2/\mathrm{ESS}$.  In this sense, effective rather than nominal sample size
governs gradient reliability.

Estimator reliability matters because an update is useful only through its effect on the
population objective.  Smooth policy-gradient analyses convert a high-probability gradient
error bound into a guaranteed improvement bound
\citep{pirotta2013adaptive,papini2022smoothing}.  Combining that argument with the
ESS-controlled error radius gives the main result of this paper: in fixed-rollout RLVR,
nominal batch size in the one-step improvement guarantee is replaced by sequence ESS.
A larger ESS produces a smaller uncertainty radius, a larger admissible step, and a larger
certified increase in population reward.

The theorem is finite-update rather than asymptotic.  It is applied conditionally at the
current policy, using an unused minibatch from a one-pass disjoint traversal.  This avoids a
global optimization argument and makes the role of sample reuse explicit.  The result also
clarifies what ESS does and does not provide.  ESS controls the amplification caused by
importance weights; the scale of the gradient integrand remains a separate problem-dependent
quantity, just as the range of a scalar integrand remains in standard importance-sampling
bounds.  Consequently, the theory yields no universal numerical ESS threshold.

We test each link in an exactly evaluable contextual bandit.  The finite population exposes
the true gradient and reward, allowing us to measure estimator error and the population
effect of each sampled update.  Lower ESS predicts larger gradient error and a sharply higher
frequency of harmful steps.  Independent redraws at frozen policies provide a complementary
bias--variance diagnostic.  We then evaluate the operational implication in language-model
RLVR, where the true gradient is unavailable but sequence ESS is observable.

\subsection{Contributions}

\begin{enumerate}
  \item We formulate the RLVR policy gradient as a vector-valued
  importance-sampling estimator and show that, under a normalized weighted
  second-moment condition, its conditional mean-squared error is bounded by
  $\sigma_g^2/\mathrm{ESS}$.
  \item We combine the ESS-controlled reliability bound with policy-objective
  smoothness to obtain a concise high-probability guarantee for the population
  improvement of an adaptive gradient step.
  \item We validate the predicted reliability transition with an exact
  contextual-bandit oracle and evaluate sequence ESS as an operational
  diagnostic in language-model training.
\end{enumerate}

\subsection{Related perspectives}

\paragraph{Importance sampling and effective sample size.}
Policy optimization via importance sampling uses the second moment of the
likelihood ratio, equivalently order-two R\'enyi divergence, to quantify the
uncertainty introduced by off-distribution evaluation
\citep{metelli2018pois,metelli2020is}.  These results show that the effective
sample count, rather than the nominal count, determines the variance of a
bounded scalar estimator.  We use the same principle for the vector-valued
policy-gradient contribution.

\paragraph{Reliable policy-gradient updates.}
Smoothness-based policy-gradient analyses lower-bound population improvement
from a finite gradient estimate and use the resulting bound to select step sizes
and sample sizes \citep{pirotta2013adaptive,papini2022smoothing}.  Our analysis
supplies the off-policy reliability radius entering that argument.  The resulting
theorem states directly how sequence ESS changes the certified update in
fixed-rollout RLVR."""

PRELIM_THEORY = r"""\section{Preliminaries}
\label{sec:setting}

\subsection{Policy-gradient estimation in RLVR}

Let $X\sim\nu$ be a prompt, let $Q(\cdot\mid X)$ be the rollout policy, and let
$P_\theta(\cdot\mid X)$ be the current policy.  A complete response is denoted by
$Y=(Y_1,\ldots,Y_T)$, and $R(X,Y)$ is its verifier reward.  The population
objective is $J(\theta):=\mathbb E_{P_\theta}[R]$.  We assume
$P_\theta(\cdot\mid X)\ll Q(\cdot\mid X)$ and write the complete-response
likelihood ratio as $W_\theta(X,Y):=P_\theta(Y\mid X)/Q(Y\mid X)$.

Let $b(X)$ be a detached prompt-level baseline, set
$A_\theta(X,Y):=R(X,Y)-b(X)$, and define the sequence score
$S_\theta(X,Y):=\nabla_\theta\log P_\theta(Y\mid X)$.  Since the response is
autoregressive, $S_\theta$ is the sum of the token scores.  With
$H_\theta:=A_\theta S_\theta$, the score identity and a change of measure give
\begin{equation}
  g(\theta):=\nabla J(\theta)
  =\mathbb E_Q[W_\theta H_\theta],
  \qquad
  \widehat g_N(\theta)
  :=\frac1N\sum_{i=1}^N W_{\theta,i}H_{\theta,i}.
  \label{eq:true-gradient}
\end{equation}
The first quantity is the population gradient and the second is its
importance-weighted estimate from $N$ rollout responses.

We analyze a single optimization phase.  The rollout batch is randomly
partitioned into disjoint minibatches before optimization, and each minibatch is
used at most once in the theoretical traversal.  Let $\mathcal F_{k-1}$ denote
all information available before update $k$.  Then the current parameter
$\theta_k$ is $\mathcal F_{k-1}$-measurable, while the unused minibatch is fresh
conditional on $\mathcal F_{k-1}$.  The estimator in
Equation~\eqref{eq:true-gradient} is therefore conditionally unbiased at the
current policy.  When several responses share a prompt or a group-relative
baseline, the intact prompt group is treated as one independent sampling unit;
Appendix~\ref{app:proofs} gives the corresponding bound.

\subsection{R\'enyi divergence and effective sample size}

For $\alpha>1$, the R\'enyi divergence from the current policy to the rollout
policy is
$D_\alpha(P_\theta\|Q):=(\alpha-1)^{-1}\log\mathbb E_Q[W_\theta^\alpha]$.
The order-two case is matched to squared estimation error:
$d_2(P_\theta\|Q):=\exp\{D_2(P_\theta\|Q)\}=\mathbb E_Q[W_\theta^2]$.
Following importance-sampling policy optimization
\citep{metelli2018pois,metelli2020is}, define the population effective sample
size and its normalized version by
\begin{equation}
  \mathrm{ESS}_N(\theta\|Q)
  :=\frac{N}{d_2(P_\theta\|Q)}
  =N\exp\{-D_2(P_\theta\|Q)\},
  \qquad
  \rho_\theta:=\frac{\mathrm{ESS}_N(\theta\|Q)}{N}.
  \label{eq:population-ess}
\end{equation}
When $P_\theta=Q$, $\mathrm{ESS}_N=N$.  As the policies separate,
$D_2(P_\theta\|Q)$ increases and the effective count decreases.  The identity
$\mathbb E_Q[(W_\theta-1)^2]=\rho_\theta^{-1}-1$ shows that this decrease is
exactly the growth of the centered ratio second moment.

\section{Theoretical analysis}
\label{sec:theory}

The analysis has two steps.  First, sequence ESS controls the error of the
importance-weighted policy-gradient estimator.  Second, objective smoothness
translates that error into a population-improvement guarantee for the realized
update.

\subsection{ESS controls gradient-estimator reliability}
\label{sec:raw}

Condition on $\mathcal F_{k-1}$ and abbreviate
$g_k:=g(\theta_k)$, $\widehat g_k:=\widehat g_N(\theta_k)$, and
$\mathrm{ESS}_k:=\mathrm{ESS}_N(\theta_k\|Q)$.  We impose the vector analogue
of the integrand-scale condition used in scalar importance-sampling bounds.

\begin{assumption}[Normalized weighted gradient moment]
\label{ass:weighted-gradient-moment}
There is a finite $\sigma_{g,k}$, measurable with respect to
$\mathcal F_{k-1}$, such that
$\mathbb E_Q[W_k^2\|H_k\|_2^2\mid\mathcal F_{k-1}]
 /\mathbb E_Q[W_k^2\mid\mathcal F_{k-1}]\le \sigma_{g,k}^2$.
\end{assumption}

Assumption~\ref{ass:weighted-gradient-moment} does not bound the population
gradient.  It separates the scale of the vector integrand from the amplification
caused by distribution mismatch.  The latter is exactly the quantity summarized
by ESS.

\begin{lemma}[Gradient reliability under policy mismatch]
\label{lem:ess-gradient-reliability}
Under Assumption~\ref{ass:weighted-gradient-moment}, the current estimator is
conditionally unbiased, its conditional mean-squared error is at most
$\sigma_{g,k}^2/\mathrm{ESS}_k$, and for any $\delta\in(0,1)$ its error is at
most $\sigma_{g,k}/\sqrt{\delta\,\mathrm{ESS}_k}$ with conditional probability
at least $1-\delta$.
\end{lemma}

Lemma~\ref{lem:ess-gradient-reliability} is the direct gradient counterpart of
the scalar importance-sampling bounds: once the gradient scale is fixed,
reliability improves at the rate $\mathrm{ESS}_k^{-1/2}$.  In normalized form,
the radius is $\sigma_{g,k}/\sqrt{\delta N\rho_k}$, so nominal batch size is
discounted exactly by current policy mismatch.

\subsection{Reliable gradients imply population improvement}
\label{sec:mse-improvement}

The next result combines Lemma~\ref{lem:ess-gradient-reliability} with the
standard quadratic lower bound for a smooth policy objective
\citep{pirotta2013adaptive,papini2022smoothing}.  Its assumptions and step size
are stated inline so that the main conclusion remains visible.

\begin{theorem}[ESS-controlled policy improvement]
\label{thm:current-ess}
Suppose Assumption~\ref{ass:weighted-gradient-moment} holds, $J$ is
$L_k$-smooth along the update segment, and $\delta\in(0,1)$.  Write
$\varepsilon_k(\delta):=\sigma_{g,k}/\sqrt{\delta\,\mathrm{ESS}_k}$ and choose
$\alpha_k:=L_k^{-1}(1-\varepsilon_k(\delta)/\|\widehat g_k\|_2)_+$, with
$\alpha_k=0$ when $\widehat g_k=0$.  Then, conditional on
$\mathcal F_{k-1}$, with probability at least $1-\delta$,
\begin{equation}
  J(\theta_k+\alpha_k\widehat g_k)-J(\theta_k)
  \ge
  \frac{1}{2L_k}
  \left(
    \|\widehat g_k\|_2
    -
    \frac{\sigma_{g,k}}
         {\sqrt{\delta\,\mathrm{ESS}_k}}
  \right)_+^2 .
  \label{eq:ess-policy-improvement}
\end{equation}
\end{theorem}

\begin{remark}[Effective rather than nominal sample size]
\label{rem:ess-interpretation}
Theorem~\ref{thm:current-ess} states the paper's central mechanism.  On-policy,
$\mathrm{ESS}_k=N$ and the uncertainty radius has the usual $N^{-1/2}$ rate.
Off-policy, $N$ is replaced by $N\exp\{-D_2(P_{\theta_k}\|Q)\}$.  A larger
sequence ESS therefore yields a smaller gradient-error radius, a larger
certified step, and a larger guaranteed improvement.  The lower bound is
strictly positive only when the observed gradient norm exceeds its uncertainty
radius.  Consequently, the relevant ESS level depends on the batch size,
confidence level, gradient scale, and current signal; no universal numerical
threshold follows from the theorem.
\end{remark}

The result is local and finite-update.  It does not require the current policy
to maximize a sampled surrogate, nor does it make an asymptotic stationarity
claim.  The one-pass condition is used only to ensure that the minibatch remains
fresh for the current adaptive policy.

\subsection{Observable reliability diagnostic}
\label{sec:practice}

Population ESS is unavailable during training.  We use the standard normalized
plug-in estimate
\begin{equation}
  \widehat\rho_k
  :=
  \frac{(\sum_{i=1}^N W_{k,i})^2}
       {N\sum_{i=1}^N W_{k,i}^2}.
  \label{eq:sample-ess}
\end{equation}
It is computed from complete-response ratios before the update.  A finite batch
can miss rare large-ratio responses and therefore overstate population support,
so $\widehat\rho_k$ is an observable diagnostic rather than a finite-sample
substitute inside Theorem~\ref{thm:current-ess}.  The numerical value $0.1$
used in the experiments is prespecified as a conservative operational event; it
is not a constant derived from Equation~\eqref{eq:ess-policy-improvement}."""

CONTEXT_INTRO = r"""\section{Contextual-bandit validation of the theory}
\label{sec:simulation}

The contextual bandit tests the two links in
Theorem~\ref{thm:current-ess}.  First, sequence ESS should track the error of the
importance-weighted policy-gradient estimator.  Second, updates made from
unreliable estimates should be more likely to reduce the true population
objective.  Because the finite population exposes both the exact gradient and
the exact reward, these quantities can be measured directly.  We additionally
compare alternative gradient estimators at frozen policies as a method-specific
bias--variance diagnostic.  The experiment does not estimate the unknown
$\sigma_{g,k}$ or directly test the adaptive step size in
Equation~\eqref{eq:ess-policy-improvement}."""

CONCLUSION = r"""\section{Conclusion}

Fixed-rollout policy optimization is reliable only to the extent that the
rollout continues to support the current learner.  This paper makes that
statement precise at the level of the policy gradient.  The gradient is a
vector-valued importance-sampling estimator, and its conditional mean-squared
error is bounded by a problem-dependent gradient scale divided by sequence
ESS.  Smoothness then converts the resulting high-probability error radius into
a lower bound on one-step population improvement.  The main conclusion is
simple: effective sample size replaces nominal batch size in the reliable
policy-gradient update.

The result explains why a rollout can support many efficient updates before
failing abruptly.  As the current policy moves away from the rollout policy,
order-two R\'enyi divergence increases, sequence ESS decreases, and the
certified gradient radius expands.  The theorem does not identify a universal
ESS threshold, because the transition also depends on gradient scale and signal
strength.  The contextual bandit confirms the predicted relation among ESS,
gradient error, and harmful updates, while the language-model experiments show
that the same sequence-level diagnostic remains informative at scale.  A
natural next step is to estimate the gradient-scale term online and use the
resulting uncertainty radius directly in adaptive update rules."""

PROOFS = r"""\section{Proofs for the theoretical results}
\label{app:proofs}

This appendix proves the gradient-reliability lemma and the population-improvement
theorem.  It then records the intact-group extension and the generic
bias--variance identity used by the frozen-policy diagnostics.

\subsection{Conditional policy-gradient identity}

Condition on $\mathcal F_{k-1}$.  The current parameter is fixed and the unused
responses are drawn from $Q$.  Since $W_k=dP_{\theta_k}/dQ$ and the baseline is
detached and prompt-measurable,
\begin{align}
  \mathbb E_Q[W_kH_k\mid\mathcal F_{k-1}]
  &=
  \mathbb E_{P_{\theta_k}}
  [(R-b(X))\nabla_\theta\log P_{\theta_k}(Y\mid X)
   \mid\mathcal F_{k-1}]\\
  &=
  \nabla J(\theta_k)
  =g_k .
  \label{eq:conditional-gradient-identity}
\end{align}
The baseline term vanishes because the conditional expectation of the score is
zero.

\subsection{Proof of Lemma~\ref{lem:ess-gradient-reliability}}

Let $Z_i:=W_{k,i}H_{k,i}$.  Conditional independence and
Equation~\eqref{eq:conditional-gradient-identity} give
\begin{align}
  \mathbb E[
    \|\widehat g_k-g_k\|_2^2
    \mid\mathcal F_{k-1}]
  &=
  \frac1N
  \mathbb E_Q[
    \|Z_1-g_k\|_2^2
    \mid\mathcal F_{k-1}]\\
  &=
  \frac1N
  \left\{
    \mathbb E_Q[
      W_k^2\|H_k\|_2^2
      \mid\mathcal F_{k-1}]
    -
    \|g_k\|_2^2
  \right\}\\
  &\le
  \frac{\sigma_{g,k}^2}
       {\mathrm{ESS}_k}.
  \label{eq:ess-gradient-mse}
\end{align}
The last line uses Assumption~\ref{ass:weighted-gradient-moment} and
$\mathrm{ESS}_k=N/\mathbb E_Q[W_k^2\mid\mathcal F_{k-1}]$.
Applying Markov's inequality to
$\|\widehat g_k-g_k\|_2^2$ yields
\[
  \Pr\left(
    \|\widehat g_k-g_k\|_2
    >
    \frac{\sigma_{g,k}}
         {\sqrt{\delta\,\mathrm{ESS}_k}}
    \,\middle|\,
    \mathcal F_{k-1}
  \right)
  \le\delta ,
\]
which proves the high-probability statement.

\subsection{Proof of Theorem~\ref{thm:current-ess}}

Let $\varepsilon_k=\varepsilon_k(\delta)$ and consider the event
$\|\widehat g_k-g_k\|_2\le\varepsilon_k$, which has conditional probability at
least $1-\delta$ by Lemma~\ref{lem:ess-gradient-reliability}.  Smoothness gives,
for any $\alpha\ge0$,
\begin{align}
  J(\theta_k+\alpha\widehat g_k)-J(\theta_k)
  &\ge
  \alpha\langle g_k,\widehat g_k\rangle
  -\frac{L_k\alpha^2}{2}\|\widehat g_k\|_2^2\\
  &\ge
  \alpha\|\widehat g_k\|_2
  \{\|\widehat g_k\|_2-\varepsilon_k\}
  -\frac{L_k\alpha^2}{2}\|\widehat g_k\|_2^2 .
  \label{eq:smoothness-with-error}
\end{align}
The second line follows from Cauchy--Schwarz:
$\langle g_k,\widehat g_k\rangle
=\|\widehat g_k\|_2^2+
\langle g_k-\widehat g_k,\widehat g_k\rangle
\ge\|\widehat g_k\|_2
(\|\widehat g_k\|_2-\varepsilon_k)$.
The right-hand side of Equation~\eqref{eq:smoothness-with-error} is a concave
quadratic in $\alpha$.  Its nonnegative maximizer is
$\alpha_k=L_k^{-1}(1-\varepsilon_k/\|\widehat g_k\|_2)_+$, with the stated
zero convention.  Substitution gives
Equation~\eqref{eq:ess-policy-improvement}.

\subsection{Intact prompt groups}

Suppose $m$ prompts are independent and each prompt has $G$ conditionally
independent responses.  Keep every prompt group intact and define its gradient
contribution by
$\Xi_{k,i}:=G^{-1}\sum_{g=1}^G W_{k,ig}H_{k,ig}$.  The minibatch estimator is
$m^{-1}\sum_i\Xi_{k,i}$.  A leave-one-out baseline is admissible because, for a
focal response, it is measurable with respect to the prompt and the other
responses and is conditionally independent of the focal score.  Jensen's
inequality gives
\[
  \|\Xi_{k,i}\|_2^2
  \le
  \frac1G\sum_{g=1}^G
  W_{k,ig}^2\|H_{k,ig}\|_2^2 .
\]
Therefore the proof of Lemma~\ref{lem:ess-gradient-reliability} applies with
$m$ independent units and the corresponding member-level weighted moment.  The
resulting bound is conservative because it counts independent prompts rather
than all responses as independent observations.

\subsection{Bias--variance identity used in the diagnostics}

Let $X_W$ be an unbiased per-unit contribution with mean $g$, and let $X_C$ be
an alternative contribution.  Write $b_C:=\mathbb E[X_C]-g$ and let
$\Sigma_W$ and $\Sigma_C$ be the corresponding covariance matrices.  For
averages of $N$ independent units,
\begin{equation}
  \operatorname{MSE}(\widehat g_C)
  <\operatorname{MSE}(\widehat g_W)
  \quad\Longleftrightarrow\quad
  \operatorname{tr}(\Sigma_W)-\operatorname{tr}(\Sigma_C)
  >
  N\|b_C\|_2^2 .
  \label{eq:crossover}
\end{equation}
Indeed,
$\operatorname{MSE}(\widehat g_W)=N^{-1}\operatorname{tr}(\Sigma_W)$ and
$\operatorname{MSE}(\widehat g_C)=\|b_C\|_2^2+
N^{-1}\operatorname{tr}(\Sigma_C)$."""

text = replace_between(text, r"\begin{abstract}", r"\end{abstract}", ABSTRACT)
text = replace_between(
    text,
    r"\section{Introduction}",
    r"\section{Contextual-bandit validation of the theory}",
    INTRO + "\n\n" + PRELIM_THEORY,
)
text = replace_between(
    text,
    r"\section{Contextual-bandit validation of the theory}",
    r"\subsection{Testbed and oracle}",
    CONTEXT_INTRO,
)
text = replace_between(text, r"\section{Conclusion}", r"\appendix", CONCLUSION)
text = replace_between(
    text,
    r"\section{Proofs for the theoretical results}",
    r"\bibliographystyle{plainnat}",
    PROOFS,
)

if r"\newtheorem{assumption}" not in text:
    text = text.replace(
        r"\newtheorem{proposition}[theorem]{Proposition}",
        r"\newtheorem{proposition}[theorem]{Proposition}" + "\n" +
        r"\newtheorem{assumption}[theorem]{Assumption}",
        1,
    )

text = text.replace("figures/figures_mains/", "figures_mains/")
text = text.replace(
    r"Theorem~\ref{thm:crossover}",
    r"Equation~\eqref{eq:crossover}",
)
text = text.replace(
    r"Equation~\eqref{eq:current-ess-certificate}",
    r"Equation~\eqref{eq:ess-policy-improvement}",
)
text = text.replace(
    r"Equation~\eqref{eq:objective-crossover}",
    r"Equation~\eqref{eq:crossover}",
)
text = text.replace(
    "This construction preserves the advantage-sign masking mechanism of\n"
    r"Proposition~\ref{prop:ppo-mask}, but applies it once to the complete-response",
    "This construction applies the advantage-sign mask once to the complete-response",
)

theory_start = text.index(r"\section{Preliminaries}")
theory_end = text.index(r"\section{Contextual-bandit validation of the theory}")
theory_text = text[theory_start:theory_end]
forbidden = re.compile(r"\b(clipping|clip|PPO|CISPO)\b", re.IGNORECASE)
match = forbidden.search(theory_text)
if match:
    raise RuntimeError(f"Forbidden intervention term in theory block: {match.group(0)}")

thm_start = theory_text.index(r"\begin{theorem}[ESS-controlled policy improvement]")
thm_end = theory_text.index(r"\end{theorem}", thm_start)
thm_text = theory_text[thm_start:thm_end]
if thm_text.count(r"\begin{equation}") != 1:
    raise RuntimeError("The main theorem must contain exactly one displayed equation.")

if "figures/figures_mains/" in text:
    raise RuntimeError("Nested figure path remains.")

path.write_text(text, encoding="utf-8")
print("Rewrote abstract, introduction, preliminaries, theory, conclusion, and proofs.")
